### ISSUE TITLE
Value of Type xxx has no member xxx Error

### ISSUE THREAD

**Issue by bleckett** [ricardopereira/ColiseuPlayer#18]
Hi just installed your pod and was trying to set the data source and delegate but I'm getting errors saying _value of type 'ColiseuPlayer' has no member delegate_ ...   or dataSource. 

        self.player.dataSource = self
        self.player.delegate = self

Do you have suggestions? 
Thanks.

<img width="983" alt="errorcoliseuplayer" src="https://cloud.githubusercontent.com/assets/8237695/13338735/3d0c230c-dbd8-11e5-9bfe-9c169d29296e.png">

**Comment by ricardopereira** [comment]
Thank you for letting me know.
I will fix this.

**Comment by ricardopereira** [comment]
Fixed #19.

**Comment by bleckett** [comment]
Wow - that was fast! Thank you!
