### ISSUE TITLE
Feature: User need to pass remote control event from View Controller to player instance

### ISSUE THREAD

**Issue by SentulAsia** [ricardopereira/ColiseuPlayer#26]
1) Right now remote control function does not receive any remote control events.

2) User need to do the following in `View Controller`:

```
import AVFoundation

override func remoteControlReceived(with event: UIEvent?) {
        // pass to player instance object
}
```

3) To declare shared instance so it can be used anywhere in the app

**Comment by SentulAsia** [comment]
@ricardopereira need your input on this...

**Comment by ricardopereira** [comment]
@SentulAsia I'm not aware of `remoteControlReceived(event:)`. Is this necessary for Headphones control for example?

**Comment by SentulAsia** [comment]
@ricardopereira its needed to control the audio from locked screen, I am thinking to create another Delegate method i.e `ColiseuPlayerRemoteControlDelegate`, and this is only delegate from AppDelegate...

**Comment by SentulAsia** [comment]
`static shared` is another way to solve this problem...

**Comment by SentulAsia** [comment]
@ricardopereira we go with shared instance approach right?

**Comment by ricardopereira** [comment]
@SentulAsia I think it's important to give the users a choice, for this lib to be more approachable to devs that prefer to handle their own instance of `ColiseuPlayer`. So, we should have a `shared` instance but the `init` could be public for those who want to create their own instance. Thanks man

**Comment by SentulAsia** [comment]
noted @ricardopereira

**Comment by ricardopereira** [comment]
About the [`remoteControlReceived(with:)`](https://developer.apple.com/documentation/uikit/uiresponder/1621118-remotecontrolreceived), the documentation says that this method is not mandatory to control the audio from the lock screen. It says it's only to "_Remote-control events originate as commands from external accessories, including headsets_". To control the lock screen, you just need the [`beginReceivingRemoteControlEvents()`](https://developer.apple.com/documentation/uikit/uiapplication/1623126-beginreceivingremotecontrolevent) and [`endReceivingRemoteControlEvents()`](https://developer.apple.com/documentation/uikit/uiapplication/1623057-endreceivingremotecontrolevents)

We can add a delegate but please have in mind to not swizzle the `UIApplication` just to have access to that method in an approachable way.

**Comment by SentulAsia** [comment]
@ricardopereira ok I'll handle the method but I leave for you on how to represent it in the README, because in my current app, I can see the playing song on the long screen, but when I tap on the pause or fast forward button, nothing happens.

That's where I realize the delegate method on AppDelegate is not handled.

**Comment by SentulAsia** [comment]
OK, sorry for the blunder, I just realized that I init the player instance from the AppDelegate, hence why the problem occurs. The method is just needed in the view controller that declared the player instance variable. @ricardopereira
