### ISSUE TITLE
Scroll duration

### ISSUE THREAD

**Issue by ricardopereira** [ricardopereira/ColiseuPlayer#4]

**Comment by SentulAsia** [comment]
@ricardopereira I've implemented this but its on remoteControlReceivedWithEvent on viewController... sorry I've just started learning swift 6 month ago without obj-c experience... So I am having difficulties thinking on how to incorporate the code into ColiseuPlayer

**Comment by ricardopereira** [comment]
@SentulAsia No problem. You doing fine.

You can add a `func remoteControlEvent(event: UIEvent)` to the ColiseuPlayer for event forwarding and then:

```
    override func remoteControlReceivedWithEvent(event: UIEvent)
    {
        player.remoteControlEvent(event)
    }
```

**Comment by SentulAsia** [comment]
ok will do that
