### ISSUE TITLE
PlayingInfo: assign player name

### ISSUE THREAD

**Issue by ricardopereira** [ricardopereira/ColiseuPlayer#6]

**Comment by SentulAsia** [comment]
@ricardopereira I wanna assign `MPMediaItemPropertyTitle` to `NSBundle.mainBundle().infoDictionary!["CFBundleName"] as String`, if it doesn't exist, fallback to `Coliseu`... Or do you have something else in mind?

**Comment by ricardopereira** [comment]
@SentulAsia Yes, sounds good. Go for it.
