### ISSUE TITLE
RemoteControl assign

### ISSUE THREAD

**Issue by ricardopereira** [ricardopereira/ColiseuPlayer#7]
- [ ] becomeFirstResponder

**Comment by SentulAsia** [comment]
@ricardopereira I've implemented this but its on viewDidLoad of the viewController... How do I incorporate this into ColiseuPlayer?

**Comment by ricardopereira** [comment]
@SentulAsia What I've in mind is to assign the responsibility of activating and deactivating the remote control to the **ColiseuPlayer**. Something like a protocol to delegate.

So, I suppose you have a `PlayerViewController` where it has a Play button, Pause, etc.

We can have this:

```
protocol ColiseuViewPlayerDelegate {
    func activateRemoteControl()
    func deactivateRemoteControl()
}
```

Assign that protocol like:

```
class PlayerViewController: UIViewController, ColiseuViewPlayerDelegate {


    // MARK: ColiseuViewPlayerDelegate

    func activateRemoteControl() {
         self.becomeFirstResponder()
    }

    func deactivateRemoteControl() {
         self.resignFirstResponder()    
    }
}
```

**Comment by SentulAsia** [comment]
@ricardopereira ok thanks... I think I know what to do now...
