### ISSUE TITLE
Swift 2.0 compatibility

### ISSUE THREAD

**Issue by SentulAsia** [ricardopereira/ColiseuPlayer#8]
I am trying to make it compatible with swift 2.0 but having trouble finding resources for this matter... keep on getting `ERROR:    177: timed out after 0.012s (515 516); mMajorChangePending=0`

**Comment by minsanity6** [comment]
@SentulAsia Did you figure out what was causing your Error: 177?

**Comment by SentulAsia** [comment]
@minsanity6 audioplayer instance is not an optional anymore, changed:

`public func audioPlayerDidFinishPlaying(player: AVAudioPlayer!, successfully flag: Bool)` to `public func audioPlayerDidFinishPlaying(player: AVAudioPlayer, successfully flag: Bool)`

(notice the bang sign is removed)

**Comment by ricardopereira** [comment]
:+1: @SentulAsia Thanks for answering.

**Comment by SentulAsia** [comment]
no probs @ricardopereira

**Comment by ahmedsafadii** [comment]
please i got the same problem here :(

https://github.com/piemonte/Player/issues/41

can u help me

**Comment by SentulAsia** [comment]
@ahmedsafadii can you check if the session is active?

**Comment by ahmedsafadii** [comment]
i can't stand what u mean ?

**Comment by SentulAsia** [comment]
I remembered seeing that error on this project, check `public func startSession()` on this project...

**Comment by ahmedsafadii** [comment]
no there's no any func named startSession

**Comment by SentulAsia** [comment]
@ahmedsafadii check `https://github.com/ricardopereira/ColiseuPlayer/blob/master/ColiseuPlayer/ColiseuPlayer.swift`

**Comment by ahmedsafadii** [comment]
:'(

https://github.com/piemonte/Player

**Comment by SentulAsia** [comment]
@ahmedsafadii yes I know, I've seen the error in your issues before in this project, I've solved it with `public func startSession()` from [this project] (`https://github.com/ricardopereira/ColiseuPlayer/blob/master/ColiseuPlayer/ColiseuPlayer.swift`), please take a look at the link i've posted and find the function that I've mentioned... Use it as a reference for your project...

**Comment by ahmedsafadii** [comment]
ok ,, thanks ;) i will try :$
